spring.application.name=backend

# PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/bubblepat_db
spring.datasource.username=postgres
spring.datasource.password=contraseña

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8081

# External APIs
api.ninjas.key=ZixswbJXwXBbF4kH1YA8kc2LqIIz0EaCiMZky3Xn

# JWT
jwt.secret=bubblepat-super-secret-key-2026-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000