--
-- PostgreSQL database dump
--

\restrict 95lAjJT2hbcf3KNAFKOiM8T1xXckymXMfWcCiZFbNIo7hdu1P3UwC5WJy4fNCls

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: pets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pets (
    id bigint NOT NULL,
    allergic_to character varying(255),
    birth_date date,
    breed character varying(255),
    daily_streak integer NOT NULL,
    last_deworming date,
    last_routine_date date,
    name character varying(255),
    species character varying(255),
    weight double precision,
    user_id bigint,
    best_streak integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.pets OWNER TO postgres;

--
-- Name: pets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reminders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reminders (
    id bigint NOT NULL,
    completed boolean NOT NULL,
    description character varying(255),
    reminder_date timestamp(6) without time zone,
    title character varying(255) NOT NULL,
    pet_id bigint
);


ALTER TABLE public.reminders OWNER TO postgres;

--
-- Name: reminders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reminders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reminders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: routines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.routines (
    id bigint NOT NULL,
    completed boolean NOT NULL,
    completed_at timestamp(6) without time zone,
    description character varying(255),
    type character varying(255) NOT NULL,
    pet_id bigint
);


ALTER TABLE public.routines OWNER TO postgres;

--
-- Name: routines_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.routines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.routines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at date,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vaccinations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vaccinations (
    id bigint NOT NULL,
    applied_date date,
    name character varying(255) NOT NULL,
    next_dose_date date,
    notes character varying(255),
    vet_name character varying(255),
    pet_id bigint
);


ALTER TABLE public.vaccinations OWNER TO postgres;

--
-- Name: vaccinations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vaccinations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vaccinations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: pets; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.pets VALUES (5, '', NULL, 'Beagle', 1, NULL, '2026-05-28', 'Firulais', 'Perro', NULL, 4, 0);
INSERT INTO public.pets VALUES (4, 'nada', '2004-12-12', 'golden retriver', 1, NULL, '2026-05-28', 'oliver', 'Perro', 40, 4, 0);
INSERT INTO public.pets VALUES (6, NULL, NULL, NULL, 0, NULL, NULL, 'Firulais', 'Perro', NULL, 7, 0);
INSERT INTO public.pets VALUES (7, NULL, NULL, NULL, 1, NULL, '2026-06-19', 'Firulais', 'Perro', NULL, 8, 1);
INSERT INTO public.pets VALUES (8, NULL, NULL, NULL, 1, NULL, '2026-06-19', 'N', 'Perro', NULL, 9, 1);
INSERT INTO public.pets VALUES (1, 'Ninguno', '2022-05-15', 'Golden Retriever', 1, '2026-01-10', '2026-06-19', 'Firulais', 'Perro', 25.5, 1, 1);
INSERT INTO public.pets VALUES (9, NULL, NULL, 'Labrador', 0, NULL, NULL, 'Luna', 'Perro', NULL, 10, 0);
INSERT INTO public.pets VALUES (10, NULL, NULL, 'Siames', 0, NULL, NULL, 'Max', 'Gato', NULL, 10, 0);
INSERT INTO public.pets VALUES (11, NULL, NULL, 'Beagle', 0, NULL, NULL, 'Rocky', 'Perro', NULL, 11, 0);


--
-- Data for Name: reminders; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.reminders VALUES (1, true, '', '2026-05-28 09:00:00', 'Dia de baño', 4);


--
-- Data for Name: routines; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.routines VALUES (1, true, '2026-05-28 16:46:45.761129', 'quiero recordatorio de alimentacion', 'feeding', 4);
INSERT INTO public.routines VALUES (3, true, '2026-06-19 01:16:29.338047', 'Desayuno', 'feeding', 7);
INSERT INTO public.routines VALUES (4, true, '2026-06-19 01:16:29.384666', 'Paseo', 'walk', 7);
INSERT INTO public.routines VALUES (2, true, '2026-06-19 01:29:40.152682', 'puede comer solo 500 gr de comida', 'feeding', 1);
INSERT INTO public.routines VALUES (5, true, '2026-06-19 01:29:58.393785', 'dar medicina a las 10', 'medicine', 1);
INSERT INTO public.routines VALUES (6, true, '2026-06-19 01:49:19.636554', NULL, 'feeding', 8);
INSERT INTO public.routines VALUES (7, true, '2026-06-19 01:49:19.662591', NULL, 'walk', 8);
INSERT INTO public.routines VALUES (8, true, '2026-06-19 01:49:19.749264', NULL, 'medicine', 8);
INSERT INTO public.routines VALUES (9, true, '2026-06-19 16:35:15.018471', '', 'walk', 1);
INSERT INTO public.routines VALUES (10, true, '2026-06-19 16:35:26.850672', 'kdklf', 'bath', 1);
INSERT INTO public.routines VALUES (11, false, NULL, 'Comer 2 veces al dia', 'Alimentacion', 9);
INSERT INTO public.routines VALUES (12, false, NULL, 'Paseo de 30 min', 'Paseo', 9);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users VALUES (1, '2026-05-28', 'ramireznavarro.maura@gmail.com', 'mau', '$2a$10$kFN/QW/898mwQG2gFf8/3uot26I7zO0GZFzRpPoewwkWRFWdGUamC');
INSERT INTO public.users VALUES (2, '2026-05-28', 'prueba@test.com', 'Prueba', '$2a$10$WkH/4exl/ltI2zo89ldvl.LhP/2owDpsHyRnBolIwa0WbqmzkJQWO');
INSERT INTO public.users VALUES (3, '2026-05-28', 'prueba2@test.com', 'Prueba2', '$2a$10$CUmm4s.M5McfniE5JaGMkeLWwPCxFJcTaRNSaGTBZYRIqNDR/FP2S');
INSERT INTO public.users VALUES (4, '2026-05-28', 'mau.ramirezn@duocuc.cl', 'maura', '$2a$10$A7TocxsRB5mBw5icwrHU9ucwOYJTV5IP5niisINzWp5dwYpi7jo/.');
INSERT INTO public.users VALUES (5, '2026-06-18', 'test@bubble.test', 'Test', '$2a$10$vfQ519pH0qZtdvqjf3LtfucFsFs9g9iKBwBg5lhaznwTR8/ngzBza');
INSERT INTO public.users VALUES (6, '2026-06-19', 'verify_b5d283@test.com', 'Test Verificacion', '$2a$10$OfkA6DX3du4oPcIV.T/1rOXLcIL.KsprEz66bkJnatk5vGo1yTwxy');
INSERT INTO public.users VALUES (7, '2026-06-19', 'streak_a08a8e@test.com', 'Test Streak', '$2a$10$ItZjcN0BfTK6R9ls66wSY.4yd9ig41SnshAiU9W8JAIzHclDzgHM6');
INSERT INTO public.users VALUES (8, '2026-06-19', 'streak_4e7780@test.com', 'Test Streak', '$2a$10$h9mfJ02mcfNQelTYxiBQXOCfsPj5jKGNTZuNJuvcVU5iAcXxC8ja.');
INSERT INTO public.users VALUES (9, '2026-06-19', 'dyn_67240f@test.com', 'T', '$2a$10$od0zS/Hx60B/9XTC8FvIOOvm6WXRZnshZTHC1hdRygoGLxFBP54im');
INSERT INTO public.users VALUES (10, '2026-06-19', 'ana@bubblepat.test', 'Ana', '$2a$10$CbEd1uC14FEqNM4JSMpi7Owk9xRaYfNYpSPGcMKd2W0BifIhQmAO6');
INSERT INTO public.users VALUES (11, '2026-06-19', 'benja@bubblepat.test', 'Benja', '$2a$10$bu8C3OVS2KaXYA2ORxt9tu3OYrhDEqVLsS3bXp63xzWh6QHng9YXm');


--
-- Data for Name: vaccinations; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.vaccinations VALUES (1, '2005-12-12', 'covid', '2007-02-12', 'se le cola vacuna', 'juan', 4);


--
-- Name: pets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pets_id_seq', 23, true);


--
-- Name: reminders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reminders_id_seq', 14, true);


--
-- Name: routines_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.routines_id_seq', 24, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 15, true);


--
-- Name: vaccinations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vaccinations_id_seq', 5, true);


--
-- Name: pets pets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pets
    ADD CONSTRAINT pets_pkey PRIMARY KEY (id);


--
-- Name: reminders reminders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reminders
    ADD CONSTRAINT reminders_pkey PRIMARY KEY (id);


--
-- Name: routines routines_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.routines
    ADD CONSTRAINT routines_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vaccinations vaccinations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vaccinations
    ADD CONSTRAINT vaccinations_pkey PRIMARY KEY (id);


--
-- Name: vaccinations fk2kv00bu89ij70upe11xsjf04k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vaccinations
    ADD CONSTRAINT fk2kv00bu89ij70upe11xsjf04k FOREIGN KEY (pet_id) REFERENCES public.pets(id);


--
-- Name: reminders fk3ua9yf0b5j07c7ye0pcmm0jfq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reminders
    ADD CONSTRAINT fk3ua9yf0b5j07c7ye0pcmm0jfq FOREIGN KEY (pet_id) REFERENCES public.pets(id);


--
-- Name: routines fk7epeiwt0kdnylnsdss6nqt563; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.routines
    ADD CONSTRAINT fk7epeiwt0kdnylnsdss6nqt563 FOREIGN KEY (pet_id) REFERENCES public.pets(id);


--
-- Name: pets fkc47kjb41qf50bwgddm024m5xn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pets
    ADD CONSTRAINT fkc47kjb41qf50bwgddm024m5xn FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 95lAjJT2hbcf3KNAFKOiM8T1xXckymXMfWcCiZFbNIo7hdu1P3UwC5WJy4fNCls

